[build]
  command = "npm run build"  # Comando para construir tu sitio web
  publish = "dist"           # Directorio que contiene los archivos estáticos generados

[[plugins]]
  package = "netlify-plugin-one"

[build.environment]
  BRANCH = "main"          

[backend]
  name = "git-gateway"       # Nombre del backend que utilizarás para gestionar el contenido

repo = "https://github.com/Theminicef/Tufuncionario.git" 
