backend:
  name: git-gateway
  branch: main # o la rama principal de tu repositorio
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "oposiciones"
    label: "Oposiciones"
    folder: "src/pages/oposiciones"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "oposiciones_sevilla"
    label: "Oposiciones Sevilla"
    folder: "src/pages/oposiciones/sevilla"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "oposiciones_madrid"
    label: "Oposiciones Madrid"
    folder: "src/pages/oposiciones/madrid"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "salarios"
    label: "Salarios"
    folder: "src/pages/blog/salarios"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "preparar_oposiciones"
    label: "Preparar Oposiciones"
    folder: "src/pages/blog/preparar-oposiciones"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "libros_recomendados"
    label: "Libros Recomendados"
    folder: "src/pages/blog/libros-recomendados"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "convocatorias"
    label: "Convocatorias"
    folder: "src/pages/blog/convocatorias"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }