backend:
  name: git-gateway
  branch: main # o la rama principal de tu repositorio
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "oposiciones"
    label: "Oposiciones"
    folder: "src/pages/oposiciones"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }